### ISSUE TITLE
Issue #2 Justin Crofoot Homework

### ISSUE THREAD

**Issue by alexandraartiles** [pos5737/hw06-Justin-Crofoot#2]
Hello! I cannot seem to find your regular R script--your code only shows up in your markdown document, but there is no commit showing your regular script.

**Comment by JustinCrofoot** [comment]
I deleted the R script when it was all in the .Rmd document. If I did not commit the R script before deleting it, I assume it is gone forever. I will make an effort to commit more often.

**Comment by alexandraartiles** [comment]
No big deal whatsoever! Luckily, your code is available within the R markdown in different chunks, so people can still technically run it!
